### ISSUE TITLE
Error setting up integration

### ISSUE THREAD

**Issue by sparkydave1981** [rob196/home-assistant-fxmarketapi#9]
## Version of the custom_component

v1.0.3

## Configuration

fx_market_api.yaml (package)
```yaml


sensor:
  - platform: fxmarketapi
    api_key: !secret fx_market_api_key
    scan_interval: 06:00:00
    foreign_exchange:
      - name: AUD to USD
        from: AUD
        to: USD
      - name: USD to AUD
        from: USD
        to: AUD
      - name: AUD to EUR
        from: AUD
        to: EUR
      - name: AUD to THB
        from: AUD
        to: THB
```

secrets.yaml
`fx_market_api_key: redacted `

**Describe the bug**
The integration won't start at all. (after initial setup and HA restart)

## Debug log

```text


2023-10-17 14:47:24.319 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fxmarketapi platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fxmarketapi/sensor.py", line 93, in setup_platform
raise Exception(f"{DEFAULT_NAME}: Invalid configuration for {NAME} platform. Error Message: {updater.error_msg}")
Exception: fxmarketapi: Invalid configuration for FXMarketAPI platform. Error Message: Error retrieving data. Status Code: 500
```

**Expected behavior**
Integration loads properly, without error

**Additional context**
Hopefully this isn't just something I've done wrong and making myself look stupid!

**Comment by rob196** [comment]
So far unable to replicate, I see you getting an HTTP 500 error though

1. Was this installed vis HACs or manually?
2. Can you browse to the below (change XXXXX in API key to your API Key)
- https://fxmarketapi.com/apilive?api_key=XXXXX&currency=AUDUSD,USDAUD,AUDEUR,AUDTHB

**Comment by sparkydave1981** [comment]
> 1. Was this installed vis HACs or manually?

Via HACS




> 2\. Can you browse to the below (change XXXXX in API key to your API Key)
> 
> * https://fxmarketapi.com/apilive?api_key=XXXXX&currency=AUDUSD,USDAUD,AUDEUR,AUDTHB

That didn't work:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by rob196** [comment]
If you are unable to browse to their API URL it is possibly a firewall blocking it?

Maybe also worth trying to Clear Cookies and Site Data?

Other than that unfortunately I am not sure what else it could be

**Comment by sparkydave1981** [comment]
Strange.  I've tried that link both at home and at work, same result.  There shouldn't be any firewall blocking HA accessing it from my house.

I'll do some more digging.

**Comment by jfrankel1** [comment]
Im also having the same problem, getting the 500 error with my API key in that link

**Comment by sparkydave1981** [comment]
I haven't had any success yet...

From my home in a web browser I still just get:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
